const STORAGE_KEY='pastel-smart-grocery-v1';
const defaultState={estimate:42,goals:['Fiber','Iron'],budget:{min:30,max:100,target:50},items:[{name:'Milk',price:6.29,nutrients:['Calcium','Protein','B12'],onDeal:true},{name:'Bananas',price:2.2,nutrients:['Potassium','Fiber'],onDeal:false},{name:'Chicken breast',price:10.99,nutrients:['Protein','Iron'],onDeal:true},{name:'Eggs',price:4.29,nutrients:['Protein','B12','Iron'],onDeal:false},{name:'White bread',price:3.29,nutrients:[],onDeal:false},{name:'Greek yogurt',price:6.2,nutrients:['Protein','Calcium','B12'],onDeal:true},{name:'Rice',price:4.25,nutrients:[],onDeal:false},{name:'Onions',price:4.49,nutrients:['Fiber','Vitamin C'],onDeal:true}],recipes:[{name:'Chicken stir-fry',icon:'🍲',ingredients:['Chicken breast','Rice','Onions','Bell peppers']},{name:'Omelette',icon:'🍳',ingredients:['Eggs','Milk','Onions']},{name:'Chicken sandwiches',icon:'🥪',ingredients:['Chicken breast','Whole grain bread','Lettuce']}]};
const foods=[{name:'Lentils',icon:'🫘',price:2.49,nutrients:['Fiber','Iron','Protein']},{name:'Berries',icon:'🫐',price:4.99,nutrients:['Fiber','Vitamin C']},{name:'Whole grain bread',icon:'🌾',price:3.79,nutrients:['Fiber','Iron']},{name:'Spinach',icon:'🥬',price:3.49,nutrients:['Iron','Vitamin C','Fiber']},{name:'Greek yogurt',icon:'🥣',price:6.2,nutrients:['Protein','Calcium','B12']},{name:'Milk',icon:'🥛',price:6.29,nutrients:['Calcium','Protein','B12']},{name:'Bananas',icon:'🍌',price:2.2,nutrients:['Potassium','Fiber']},{name:'Eggs',icon:'🥚',price:4.29,nutrients:['Protein','B12','Iron']},{name:'Oranges',icon:'🍊',price:4.49,nutrients:['Vitamin C','Fiber','Potassium']},{name:'Bell peppers',icon:'🫑',price:2.49,nutrients:['Vitamin C','Fiber']},{name:'Lettuce',icon:'🥬',price:2.99,nutrients:['Fiber','Vitamin K']}];
const cloneDefault=()=>JSON.parse(JSON.stringify(defaultState));
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!saved)return cloneDefault();return{...cloneDefault(),...saved,budget:{...cloneDefault().budget,...(saved.budget||{})},items:Array.isArray(saved.items)?saved.items:cloneDefault().items,goals:Array.isArray(saved.goals)?saved.goals:cloneDefault().goals,recipes:Array.isArray(saved.recipes)?saved.recipes:cloneDefault().recipes}}catch{return cloneDefault()}}
let state=loadState();
const saveState=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const money=v=>`$${Number(v||0).toFixed(2)}`;
const recalcEstimate=()=>state.estimate=state.items.reduce((s,i)=>s+Number(i.price||0),0);
const hasItem=name=>state.items.some(i=>i.name.toLowerCase()===name.toLowerCase());
const findFood=name=>foods.find(f=>f.name.toLowerCase()===name.toLowerCase());
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>t.classList.remove('show'),2200)}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.querySelectorAll('.go-page').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
function addItem(name,price=0,nutrients=[],onDeal=false){const clean=name.trim();if(!clean||hasItem(clean))return false;state.items.push({name:clean,price:Number(price||0),nutrients:[...nutrients],onDeal});recalcEstimate();saveState();renderAll();showToast(`${clean} added`);return true}
function removeItem(name){const idx=state.items.findIndex(i=>i.name===name);if(idx<0)return;state.items.splice(idx,1);recalcEstimate();saveState();renderAll();showToast(`${name} removed`)}
function renderList(){const list=document.getElementById('listRows');list.innerHTML='';state.items.forEach(item=>{const row=document.createElement('div');row.className='item-row';const left=document.createElement('div');const name=document.createElement('div');name.className='item-name';name.textContent=`🛒 ${item.name}`;const meta=document.createElement('div');meta.className='item-meta';const bits=[];if(item.nutrients?.length)bits.push(item.nutrients.join(' · '));if(item.price)bits.push(money(item.price));if(item.onDeal)bits.push('on deal');meta.textContent=bits.join(' · ')||'Shopping item';left.append(name,meta);const x=document.createElement('button');x.className='remove';x.type='button';x.textContent='×';x.setAttribute('aria-label',`Remove ${item.name}`);x.addEventListener('click',()=>removeItem(item.name));row.append(left,x);list.append(row)});document.getElementById('itemCount').textContent=state.items.length;document.getElementById('estTotal').textContent=money(state.estimate);document.getElementById('dealCount').textContent=state.items.filter(i=>i.onDeal).length;document.getElementById('homeListSummary').textContent=`${state.items.length} items · est. ${money(state.estimate)}`;document.getElementById('budgetCurrent').textContent=money(state.estimate)}
function renderGoals(){const wrap=document.getElementById('goalWrap');wrap.innerHTML='';state.goals.forEach(goal=>{const chip=document.createElement('span');chip.className='chip goal';const text=document.createElement('span');text.textContent=goal;const x=document.createElement('button');x.type='button';x.textContent='×';x.setAttribute('aria-label',`Remove ${goal}`);x.addEventListener('click',()=>{state.goals=state.goals.filter(g=>g!==goal);saveState();renderAll()});chip.append(text,x);wrap.append(chip)});const bg=document.getElementById('budgetGoals');bg.innerHTML='';if(!state.goals.length)bg.innerHTML='<span class="small-muted">No nutrient goals selected.</span>';else state.goals.forEach(g=>{const c=document.createElement('span');c.className='chip';c.textContent=`${g} ✓`;bg.append(c)})}
function renderFoodSuggestions(){const wrap=document.getElementById('foodSuggestions');wrap.innerHTML='';const matches=foods.map(f=>({...f,matched:f.nutrients.filter(n=>state.goals.includes(n))})).filter(f=>f.matched.length).sort((a,b)=>b.matched.length-a.matched.length||a.price-b.price);document.getElementById('foodCount').textContent=`${matches.length} suggestions`;if(!matches.length){wrap.innerHTML='<div class="search-empty">Add a nutrient goal to see matching foods.</div>';document.getElementById('gapTitle').textContent='No nutrition goal selected';document.getElementById('gapCopy').textContent='Choose what the list should improve';return}matches.forEach((food,index)=>{const card=document.createElement('article');card.className='suggestion';if(index===0)card.style.background='var(--green-soft)';const head=document.createElement('div');head.style.display='flex';head.style.justifyContent='space-between';head.style.gap='12px';const left=document.createElement('div');const title=document.createElement('div');title.className='suggestion-title';title.textContent=`${food.icon} ${food.name}`;const tags=document.createElement('div');tags.className='tags';food.matched.forEach(n=>{const tag=document.createElement('span');tag.className='tag';tag.textContent=n;tags.append(tag)});left.append(title,tags);const price=document.createElement('div');price.className='small-muted';price.textContent=`~${money(food.price)}`;head.append(left,price);const btn=document.createElement('button');btn.className='inline-btn';btn.type='button';btn.textContent=hasItem(food.name)?'Already on list':'Add to list';btn.disabled=hasItem(food.name);btn.addEventListener('click',()=>addItem(food.name,food.price,food.nutrients));card.append(head,btn);wrap.append(card)});const first=state.goals[0],notOnList=matches.filter(f=>!hasItem(f.name));document.getElementById('gapTitle').textContent=`Your list is still low in ${first.toLowerCase()}`;document.getElementById('gapCopy').textContent=`${notOnList.length} foods could improve it`}
function nutrientCoverageWithout(itemName,goal){return state.items.filter(i=>i.name!==itemName).some(i=>i.nutrients?.includes(goal))}
function safeCut(item){const relevant=(item.nutrients||[]).filter(n=>state.goals.includes(n));return relevant.every(g=>nutrientCoverageWithout(item.name,g))}
function renderBudgetCuts(){const wrap=document.getElementById('cutList');wrap.innerHTML='';const amount=Math.max(0,state.estimate-state.budget.target);const candidates=state.items.filter(i=>i.price>0&&safeCut(i)).sort((a,b)=>b.price-a.price);if(!candidates.length){wrap.innerHTML='<div class="search-empty">No safe cuts found for your current nutrient goals.</div>';return}let running=0;candidates.slice(0,4).forEach(item=>{running+=item.price;const relevant=(item.nutrients||[]).filter(n=>state.goals.includes(n));const card=document.createElement('article');card.className='suggestion';const head=document.createElement('div');head.style.display='flex';head.style.justifyContent='space-between';head.style.gap='10px';const left=document.createElement('div');const title=document.createElement('div');title.className='suggestion-title';title.textContent=item.name;const copy=document.createElement('div');copy.className='card-copy';copy.textContent=relevant.length?`Other foods still cover ${relevant.join(' + ')}.`:'Low contribution to your selected nutrient goals.';left.append(title,copy);const saving=document.createElement('strong');saving.className='green-text';saving.textContent=`−${money(item.price)}`;head.append(left,saving);const btn=document.createElement('button');btn.className='inline-btn';btn.type='button';btn.textContent='Skip this item';btn.addEventListener('click',()=>removeItem(item.name));card.append(head,btn);if(amount>0&&running>=amount){const note=document.createElement('div');note.className='notice';note.textContent='Removing items through here would reach your current target.';card.append(note)}wrap.append(card)})}
function renderBudget(){const min=document.getElementById('budgetMin'),max=document.getElementById('budgetMax'),slider=document.getElementById('budgetRange');min.value=state.budget.min;max.value=state.budget.max;slider.min=state.budget.min;slider.max=state.budget.max;slider.value=state.budget.target;document.getElementById('budgetTarget').textContent=`$${state.budget.target}`;const diff=state.budget.target-state.estimate;const msg=document.getElementById('budgetMessage');msg.innerHTML=diff>=0?`<span class="green-text">${money(diff)} remaining</span>`:`Need to cut ${money(Math.abs(diff))}`}
function renderRecipes(){const wrap=document.getElementById('recipeList');const q=document.getElementById('recipeSearch').value.trim().toLowerCase();wrap.innerHTML='';const rs=state.recipes.filter(r=>r.name.toLowerCase().includes(q));if(!rs.length){wrap.innerHTML='<div class="search-empty">No recipes match that search.</div>';return}rs.forEach(r=>{const missing=r.ingredients.filter(name=>!hasItem(name));const card=document.createElement('article');card.className='recipe';const head=document.createElement('div');head.style.display='flex';head.style.justifyContent='space-between';head.style.gap='10px';const left=document.createElement('div');const title=document.createElement('div');title.className='recipe-title';title.textContent=`${r.icon||'🍴'} ${r.name}`;const copy=document.createElement('div');copy.className='card-copy';copy.textContent=missing.length?`Missing: ${missing.join(', ')}`:'No extra shopping needed';left.append(title,copy);const badge=document.createElement('span');badge.className='chip';badge.textContent=missing.length?`${missing.length} missing`:'Ready';head.append(left,badge);card.append(head);if(missing.length){const btn=document.createElement('button');btn.className='inline-btn';btn.type='button';btn.textContent='Add missing ingredients';btn.addEventListener('click',()=>missing.forEach(name=>{const f=findFood(name);addItem(name,f?.price||0,f?.nutrients||[])}));card.append(btn)}wrap.append(card)})}
function renderHomeMealOpportunity(){const recipe=state.recipes.find(r=>r.name==='Chicken stir-fry')||state.recipes[0];if(!recipe)return;const missing=recipe.ingredients.filter(n=>!hasItem(n));const title=document.getElementById('mealOpportunityTitle'),copy=document.getElementById('mealOpportunityCopy'),action=document.getElementById('homeMealAction');if(!missing.length){title.textContent=`${recipe.name} is ready`;copy.textContent='No extra shopping needed';action.textContent='View meals';action.onclick=()=>showPage('mealsPage');return}title.textContent=`Add ${missing.length} item${missing.length===1?'':'s'} to complete ${recipe.name}`;copy.textContent=missing.length===1?`Only ${missing[0]} missing`:`${missing.join(', ')} missing`;action.textContent=missing.length===1?'Add item':'Add missing items';action.onclick=()=>missing.forEach(name=>{const f=findFood(name);addItem(name,f?.price||0,f?.nutrients||[])})}
function renderAll(){recalcEstimate();renderList();renderGoals();renderFoodSuggestions();renderBudget();renderBudgetCuts();renderRecipes();renderHomeMealOpportunity();saveState()}
document.getElementById('itemAdd').addEventListener('click',()=>{const i=document.getElementById('itemInput'),v=i.value.trim();if(v){addItem(v);i.value=''}});document.getElementById('itemInput').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('itemAdd').click()});
document.getElementById('applySaving').addEventListener('click',()=>{if(hasItem('Greek yogurt')){removeItem('Greek yogurt');document.getElementById('saveCard').innerHTML='<div class="card-title">✓ Saving applied</div><div class="card-copy">Greek yogurt was removed from this trip.</div>'}else showToast('Greek yogurt is already off your list')});
document.getElementById('quickAdd').addEventListener('click',()=>{showPage('listPage');setTimeout(()=>document.getElementById('itemInput').focus(),120)});document.getElementById('repeatLast').addEventListener('click',()=>{[{name:'Apples',price:3.99,nutrients:['Fiber','Vitamin C']},{name:'Coffee',price:8.99,nutrients:[]},{name:'Cheese',price:6.49,nutrients:['Protein','Calcium']}].forEach(i=>addItem(i.name,i.price,i.nutrients));showToast('Last-list items added')});document.getElementById('receipt').addEventListener('click',()=>document.getElementById('receiptSheet').classList.add('show'));document.getElementById('closeSheet').addEventListener('click',()=>document.getElementById('receiptSheet').classList.remove('show'));document.getElementById('fakeScan').addEventListener('click',()=>{document.getElementById('receiptSheet').classList.remove('show');state.items.forEach(i=>{if(!i.price)i.price=2.99});recalcEstimate();saveState();renderAll();showToast('Receipt prices updated')});
function addGoal(value){const clean=value.trim();if(!clean)return;const canonical=foods.flatMap(f=>f.nutrients).find(n=>n.toLowerCase()===clean.toLowerCase())||clean.charAt(0).toUpperCase()+clean.slice(1);if(!state.goals.some(g=>g.toLowerCase()===canonical.toLowerCase()))state.goals.push(canonical);document.getElementById('nutInput').value='';saveState();renderAll()}
document.getElementById('nutAdd').addEventListener('click',()=>addGoal(document.getElementById('nutInput').value));document.getElementById('nutInput').addEventListener('keydown',e=>{if(e.key==='Enter')addGoal(e.currentTarget.value)});document.querySelectorAll('.preset').forEach(b=>b.addEventListener('click',()=>addGoal(b.dataset.n)));
function syncBudget(){const minI=document.getElementById('budgetMin'),maxI=document.getElementById('budgetMax'),slider=document.getElementById('budgetRange');let min=Math.max(0,Number(minI.value)||0),max=Math.max(min+1,Number(maxI.value)||min+1),target=Number(slider.value)||min;target=Math.max(min,Math.min(max,target));state.budget={min,max,target};saveState();renderBudget();renderBudgetCuts()}
document.getElementById('budgetRange').addEventListener('input',e=>{state.budget.target=Number(e.currentTarget.value);saveState();renderBudget();renderBudgetCuts()});document.getElementById('budgetMin').addEventListener('change',syncBudget);document.getElementById('budgetMax').addEventListener('change',syncBudget);document.getElementById('recipeSearch').addEventListener('input',renderRecipes);document.getElementById('saveRecipe').addEventListener('click',()=>{const n=document.getElementById('recipeName').value.trim(),raw=document.getElementById('recipeIngredients').value.trim();if(!n||!raw){showToast('Add a recipe name and ingredients');return}state.recipes.push({name:n,icon:'🍴',ingredients:raw.split(',').map(v=>v.trim()).filter(Boolean)});document.getElementById('recipeName').value='';document.getElementById('recipeIngredients').value='';saveState();renderRecipes();renderHomeMealOpportunity();showToast('Recipe saved')});
renderAll();
